on:
  pull_request:
    branches:
    - '*'
  push:
    branches:
      - master
name: Test
jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x
    - name: Checkout code
      uses: actions/checkout@v2
    - run: go run ./cmd/gofaker address
    - run: go run ./cmd/gofaker adult --min=18 --max=99 age
    - run: go run ./cmd/gofaker city
    - run: go run ./cmd/gofaker country --short
    - run: go run ./cmd/gofaker email
    - run: go run ./cmd/gofaker guid
    - run: go run ./cmd/gofaker name first
    - run: go run ./cmd/gofaker now
    - run: go run ./cmd/gofaker password
    - run: go run ./cmd/gofaker phone
    - run: go run ./cmd/gofaker zip
    - run: go run ./cmd/gofaker sex
    - run: go run ./cmd/gofaker state
    - run: go run ./cmd/gofaker street
    - run: go run ./cmd/gofaker street2
    - run: go run ./cmd/gofaker ssn
